[package]
name = "rgss"
version = "0.1.0"
authors = ["AndrewMonteith <andrewmonteith1999@gmail.com>"]
build = "build.rs"

[dependencies]
reqwest = { version = "0.8.6" }
serde_json = "1.0"
lazy_static = "1.0"

[build-dependencies]
peg = { version = "0.5" }
